[features]
seeds = true
skip-lint = false

[programs.localnet]
libreplex_metadata="AJ5Hh5q4HegZWWu1ScY7ZRA6zELXmRzEWS5EXFSKqBC6"
libreplex_default_renderer="rndbQFmFfiQ4tTG9QPhfJeq1J9fLCSBMAPj3EbLQ7Co"
libreplex_inscriptions="inscokhJarcjaEs59QbQ7hYjrKz25LEPRfCbP8EmdUp"
libreplex_creator="78deTr7qycJ6498vSd3pNMhdCKKWxMipniitVHQcM8RM"
libreplex_shop="ListjawGEdhxuAErSyYwcTEGWQswFoi6FScnGG1RKSB"
libreplex_creator_controls="G9whLiLT9nSkxwWzWvbiKKrTL6yWxvzh2UXqNht5VXqV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 100000

[test.validator]
#url = "https://api.devnet.solana.com"
url = "http://localhost:8899"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/**/**/tests/**/*.ts"
#test_rust = "mocha -t 1000000 tests2/"
#test= "mocha -t 1000000 tests"
